//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp25
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string BookingStatusCode { get; set; }
    
        public virtual RoomStatu RoomStatu { get; set; }
    }
}
